#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

config_dir="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml"
config_file="$config_dir/xfce4-terminal.xml"

mkdir -p "$config_dir"
cp $script_dir/xfce4-terminal.xml $config_file
echo "File created at $config_file"
