#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="browser-apps"
app_name_fmt="\033[1;32m${app_name}\033[0m"

echo -e "[${app_name_fmt}] Creating YouTube web app shortcut..."
sudo sh -c 'echo "chromium --app=https://youtube.com" > /bin/youtube && chmod +x /bin/youtube'

echo -e "[${app_name_fmt}] Creating Notion web app shortcut..."
sudo sh -c 'echo "chromium --app=https://www.notion.so/" > /bin/notion && chmod +x /bin/notion'

echo -e "[${app_name_fmt}] Creating ChatGPT web app shortcut..."
sudo sh -c 'echo "chromium --app=https://chat.openai.com/" > /bin/gptchat && chmod +x /bin/gptchat'

echo -e "[${app_name_fmt}] Creating YouTube Music web app shortcut..."
sudo sh -c 'echo "microsoft-edge-stable --app=https://music.youtube.com" > /bin/ytmusic && chmod +x /bin/ytmusic'

echo -e "[${app_name_fmt}] Browser web apps installation completed."
