#!/bin/bash
sudo -v

yay_install() {
    # Verificar si yay ya está instalado
    if ! command -v yay &>/dev/null; then
        echo "yay is not installed. Installing..."
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si --noconfirm
        cd -
        rm -rf yay
    else
        echo "yay is already installed."
    fi
}

install_minimal_apps() {
    packages=(
        base-devel
        chromium
        gstreamer
        gst-plugins-ugly
        ntfs-3g
        exfat-utils
        fuse-exfat
        xscreensaver
        fish
        pamac
        nano
        i3
        neofetch
        htop
        rofi
        dmenu
        xfce4-terminal
        clipit
        flameshot
        udiskie
        dunst
        mousepad
        nitrogen
        network-manager-applet
        thunar
        picom
        octopi
        octopi-notifier-qt5
    )

    yay -Sy
    yay -S --noconfirm "${packages[@]}"
}

install_complete_apps() {
    packages=(
        visual-studio-code-bin
        jdk8-openjdk
        google-chrome
        microsoft-edge-stable-bin
        brave-bin
        intellij-idea-community-edition
        intellij-idea-ultimate-edition
        intellij-idea-ultimate-edition-jre
        dbeaver
        maven
        discord
        slack-desktop
    )

    yay -S --noconfirm "${packages[@]}"
}

install_fish() {
    # Verificar si fish ya está instalado
    if which fish &>/dev/null; then
        echo "Fish is already installed."
    else
        # Si fish no está instalado, instalarlo y configurarlo
        curl -L https://get.oh-my.fish | fish
        omf install agnoster
    fi
}

config_dunst() {
    local dunstrc_path="$HOME/.config/dunst/dunstrc"
    
    # Verificar si el archivo dunstrc ya existe
    if [ -f "$dunstrc_path" ]; then
        echo "The dunst configuration file already exists."
    else
        # Si el archivo dunstrc no existe, crearlo y configurarlo
        mkdir -p ~/.config/dunst && echo -e "[global]\nfont = Sans 15" > "$dunstrc_path"
        echo "The dunst configuration file has been created."
    fi
}

# Función para configurar picom
config_picom() {
    # Realizar copia de seguridad del archivo de configuración existente, si lo hay
    if [ -f "/etc/xdg/picom.conf" ]; then
        sudo mv /etc/xdg/picom.conf /etc/xdg/picom.conf.bak
    fi

    # Crear o editar el archivo de configuración de picom
    sudo nano /etc/xdg/picom.conf <<EOF
# Shadows
shadow = true;
shadow-radius = 8;
shadow-opacity = 0.6;
shadow-offset-x = -3;
shadow-offset-y = -3;
shadow-exclude = [
  "class_g ?= 'i3-frame'"
];
# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;
# Transparency / Opacity
inactive-opacity = 1;
frame-opacity = 1.0;
inactive-opacity-override = false;
detect-client-opacity = true;
focus-exclude = [ "class_g = 'Cairo-clock'" ];
opacity-rule = [
  "90:class_g = 'URxvt'",
  "97:class_g = 'Anki'",
  "70:class_g = 'i3bar'"
];
# General settings
backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
# refresh-rate = 75;
use-ewmh-active-win = true;
detect-transient = true;
detect-client-leader = true;
use-damage = true;
log-level = "warn";
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 1; focus = true; full-shadow = false; };
  dock = { shadow = false; opacity: 0.8; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 1; }
};
unredir-if-possible = false;

blur-background = true;
blur-method = "dual_kawase";
blur-strength = 1;
EOF
}

create_xinitrc() {
    cat <<EOF >"$HOME/.xinitrc"
setxkbmap -layout es

nm-applet &
clipit &
flameshot &
udiskie --tray &
dunst &
picom &
xscreensaver &
pamac-tray &
usr/bin/octopi-notifier &

exec i3
EOF
}

generate_xfce4_terminal_config() {
    local config_dir="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml"
    local config_file="$config_dir/xfce4-terminal.xml"
    local config_content='<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-terminal" version="1.0">
  <property name="run-custom-command" type="bool" value="true"/>
  <property name="custom-command" type="string" value="/bin/fish"/>
  <property name="command-login-shell" type="bool" value="false"/>
</channel>
'

    mkdir -p "$config_dir" || { echo "Error: Unable to create directory $config_dir"; exit 1; }
    echo "$config_content" > "$config_file" || { echo "Error: Unable to create file $config_file"; exit 1; }
    echo "Xfce4-terminal configuration file generated at: $config_file"
}

yay_install

install_minimal_apps

if [ "$1" == "complete" ]; then
    install_complete_apps
fi

config_dunst
config_picom
create_xinitrc
install_fish
generate_xfce4_terminal_config
