#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"
sudo -v
sudo pacman -Sy

install_oh_my_fish() {
    cd ~
    git clone https://github.com/oh-my-fish/oh-my-fish
    cd oh-my-fish/bin
    chmod +x install
    ./install --noninteractive
    fish -c "omf install agnoster"
}

config_picom() {
    sudo rm /etc/xdg/picom.conf
    cd $script_dir
    sudo cp picom.conf /etc/xdg/picom.conf
}

generate_xfce4_terminal_config() {
    local config_dir="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml"
    local config_file="$config_dir/xfce4-terminal.xml"

    mkdir -p "$config_dir"
    cd $script_dir
    cp xfce4-terminal.xml $config_file
    echo "File created at $config_file"
}

install_bumblebee_status() {
    cd ~/.config
    git clone https://github.com/tobi-wan-kenobi/bumblebee-status
}

copy_i3_config_file() {
    cd $script_dir
    mkdir -p ~/.config/i3
    cp i3/config ~/.config/i3/config
}

install_dark_theme() {
    cd $script_dir
    cp gtkrc-2.0 ~/.gtkrc-2.0
}

generate_neofetch_config() {
    neofetch_config_dir=~/.config/neofetch

    if [ ! -d "$neofetch_config_dir" ]; then
        mkdir -p "$neofetch_config_dir"
    fi

    cp neofetch.conf "$neofetch_config_dir/config.conf"
}

add_neofetch_in_terminals() {
    echo "neofetch" >> ~/.bashrc
    echo "neofetch" >> ~/.config/fish/config.fish
}

create_browser_apps() {
    sudo sh -c 'echo "chromium --app=https://youtube.com" > /bin/youtube && chmod +x /bin/youtube'
    sudo sh -c 'echo "chromium --app=https://www.notion.so/" > /bin/notion && chmod +x /bin/notion'
    sudo sh -c 'echo "chromium --app=https://network.wwe.com/" > /bin/wwe && chmod +x /bin/wwe'
    sudo sh -c 'echo "chromium --app=https://chat.openai.com/" > /bin/gptchat && chmod +x /bin/gptchat'
    sudo sh -c 'echo "microsoft-edge-stable --app=https://music.youtube.com" > /bin/ytmusic && chmod +x /bin/ytmusic'
}

install_redshift() {
    cd $script_dir
    cp redshift.conf ~/.config/redshift.conf
}

./yay/install
./apps/minimal-install

if [ "$1" == "extra" ]; then
    ./apps/extra-install
fi

./lock/install
./dunst/install
# config_picom
./xinitrc/install
generate_xfce4_terminal_config
install_bumblebee_status
copy_i3_config_file
install_oh_my_fish
install_dark_theme
generate_neofetch_config
add_neofetch_in_terminals
./nitrogen/install
create_browser_apps
install_redshift
