#!/bin/bash

# Ruta al directorio de configuración de xfce4-terminal
config_dir="$HOME/.config/xfce4/terminal"

# Verificar si el directorio de configuración existe
if [ ! -d "$config_dir" ]; then
    # Crear el directorio de configuración si no existe
    mkdir -p "$config_dir"
fi

# Ruta al archivo de configuración de xfce4-terminal
config_file="$config_dir/terminalrc"

# Verificar si el archivo de configuración existe
if [ ! -f "$config_file" ]; then
    # Crear el archivo de configuración si no existe
    touch "$config_file"
fi

# Actualizar el shell predeterminado en el archivo de configuración
echo "SHELL=fish" > "$config_file"
echo "xfce4-terminal shell set to fish."
