#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="pc-polybar"
app_name_fmt="\033[1;32m${app_name}\033[0m"
config_file="$HOME/.config/polybar/config.ini"

echo -e "[${app_name_fmt}] Configuring PC-specific polybar modules..."

if [ -f "$config_file" ]; then
    sed -i "s/\$MODULES_RIGHT/polyrestart pulseaudio systray clock/g" "$config_file"
    echo -e "[${app_name_fmt}] PC polybar configuration completed."
else
    echo -e "[${app_name_fmt}] \033[0;31mError:\033[0m $config_file no encontrado o no es un archivo regular."
fi
