#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="search-script"
app_name_fmt="\033[1;32m${app_name}\033[0m"

echo -e "[${app_name_fmt}] Installing search script..."
sudo cp $script_dir/search /usr/bin/search

echo -e "[${app_name_fmt}] Setting execution permissions..."
sudo chmod +x /usr/bin/search

echo -e "[${app_name_fmt}] Search script installation completed."
