#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="notebook-polybar"
app_name_fmt="\033[1;32m${app_name}\033[0m"

echo -e "[${app_name_fmt}] Configuring notebook-specific polybar modules..."
sed -i "s/\$MODULES_RIGHT/polyrestart redshift brightness battery pulseaudio systray clock/g" "$HOME/.config/polybar/config.ini"

echo -e "[${app_name_fmt}] Notebook polybar configuration completed."
