#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

dunstrc_path="$HOME/.config/dunst/dunstrc"
    
# Verificar si el archivo dunstrc ya existe
if [ -f "$dunstrc_path" ]; then
    echo "The dunst configuration file already exists."
else
    # Si el archivo dunstrc no existe, crearlo y configurarlo
    mkdir -p ~/.config/dunst
    cp $script_dir/dunstrc $dunstrc_path
    echo "The dunst configuration file has been created."
fi
