#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="dunst"
app_name_fmt="\033[1;32m${app_name}\033[0m"

dunstrc_path="$HOME/.config/dunst/dunstrc"

echo -e "[${app_name_fmt}] Checking dunst configuration..."
if [ -f "$dunstrc_path" ]; then
    echo -e "[${app_name_fmt}] Dunst configuration file already exists."
else
    echo -e "[${app_name_fmt}] Creating dunst configuration directory..."
    mkdir -p ~/.config/dunst
    
    echo -e "[${app_name_fmt}] Copying dunst configuration file..."
    cp $script_dir/dunstrc $dunstrc_path
fi

echo -e "[${app_name_fmt}] Dunst setup completed."
