#!/bin/bash

# Source utils.sh
source "$(dirname "$0")/../lib/utils.sh"

app_name="i3"
repo_url="https://github.com/prezdev88/i3-config"
target_dir="$HOME/.config/i3"

log_info "Starting installation for $app_name..."

install_from_git "$repo_url" "$target_dir"

if [ $? -eq 0 ]; then
    log_success "$app_name setup completed successfully."
else
    log_error "$app_name setup failed."
    exit 1
fi

