#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

neofetch_config_dir=~/.config/neofetch

if [ ! -d "$neofetch_config_dir" ]; then
    mkdir -p "$neofetch_config_dir"
fi

cp $script_dir/neofetch.conf "$neofetch_config_dir/config.conf"
