#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

cd $HOME
git clone https://github.com/oh-my-fish/oh-my-fish
chmod +x $HOME/oh-my-fish/bin/install
cd $HOME/oh-my-fish/bin
./install --noninteractive
fish -c "omf install agnoster"
cd $HOME/autoarch-bootstrap
