#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

cp $script_dir/Xresources ~/.Xresources
cp $script_dir/xinitrc ~/.xinitrc
sed -i "s/\$DPI/90/g" "$HOME/.config/polybar/config.ini"

# Añadir xrdb .Xresources & en .xinitrc antes de exec i3
