#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="polybar"
app_name_fmt="\033[1;32m${app_name}\033[0m"

polybar_dir="$HOME/.config/polybar"

echo -e "[${app_name_fmt}] Checking polybar configuration directory..."
if [ ! -d "$polybar_dir" ]; then
    echo -e "[${app_name_fmt}] Creating polybar configuration directory..."
    mkdir -p "$polybar_dir"
fi

echo -e "[${app_name_fmt}] Copying polybar scripts..."
cp -r $script_dir/scripts $polybar_dir

echo -e "[${app_name_fmt}] Copying polybar configuration..."
cp $script_dir/config.ini $polybar_dir

echo -e "[${app_name_fmt}] Copying polybar launch script..."
cp $script_dir/launch.sh $polybar_dir

echo -e "[${app_name_fmt}] Polybar setup completed."
