#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

declare -a packages

while IFS= read -r line; do
    packages+=("$line")
done < $script_dir/extra

yay -Sy
yay -S --noconfirm "${packages[@]}"
