#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="redshift"
app_name_fmt="\033[1;32m${app_name}\033[0m"

echo -e "[${app_name_fmt}] Installing redshift configuration..."
cp $script_dir/redshift.conf ~/.config/redshift.conf

echo -e "[${app_name_fmt}] Redshift configuration completed."
