#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="not-2k-setup"
app_name_fmt="\033[1;32m${app_name}\033[0m"

echo -e "[${app_name_fmt}] Configuring standard DPI in polybar..."
sed -i "s/\$DPI/90/g" "$HOME/.config/polybar/config.ini"

echo -e "[${app_name_fmt}] Standard DPI setup completed."