#!/bin/bash
script_dir="$(cd "$(dirname "$0")" && pwd)"

app_name="fix-cursor"
app_name_fmt="\033[1;32m${app_name}\033[0m"

echo -e "[${app_name_fmt}] Copying cursor configuration..."
cp $script_dir/Xresources ~/.Xresources

echo -e "[${app_name_fmt}] Cursor configuration setup completed."
